config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'mail', to: 'mail#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mail.rb
# frozen_string_literal: true

# Mails model
class Mail < ApplicationRecord
  belongs_to :user
  validates_presence_of :body
  scope :recent_messages, -> { Mail.last(25) }
end

app/models/user.rb
# frozen_string_literal: true

# model for users
class User < ApplicationRecord
  has_many :mails
  validates :name, presence: true, uniqueness: { case_senstive: false },
                   length: { in: 5..25 }
  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application controller
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    return false unless session[:user_id]

    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def require_user
    return if logged_in?

    flash[:error] = 'You must be logged in to perform the action'
    redirect_to login_path
  end
end

app/controllers/chatroom_controller.rb
# frozen_string_literal: true

# chatroom controller
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @mail = Mail.new
    @mails = Mail.recent_messages
  end
end

app/controllers/mail_controller.rb
# frozen_string_literal: true

# Messages controller
class MailController < ApplicationController
  before_action :require_user

  def create
    mail = current_user.mails.build(whitelist_params)
    return unless mail.save

    ActionCable.server.broadcast 'chatroom_channel', mail: mail_render(mail)
  end

  private

  def whitelist_params
    params.require(:mail).permit(:body)
  end

  def mail_render(mail)
    render(partial: 'mails/mail', locals: { mail: mail })
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# sessions controller
class SessionsController < ApplicationController
  def new
    redirect_to root_path if logged_in?
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user&.authenticate(params[:session][:password])
      create_session(user)
    else
      flash.now[:error] = 'Invalid credentials'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logged out successfully'
    redirect_to login_path
  end

  private

  def create_session(user)
    session[:user_id] = user.id
    flash[:success] = 'Logged in successfully'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<div class="ui grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="ui content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @mails %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(:mail, html: {id: "create_message", class: "ui reply form", role: "form"}, url: mail_path, remote: true) do |f| %>
          <div class="ui fluid icon input">
            <%= f.text_field :body, placeholder: "Say something.."%>
            <%= f.button '<i class="bordered inverted teal edit link large icon"></i>'.html_safe, class: "compose_button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid card chatbox">
      <div class="ui content">
        <div class="ui secondary vertical menu">
          <a class="item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<h2 class="ui center aligned icon header">
  Chatroom
  <i class="comment teal icon"></i>
  Where the real talking happens!
</h2>

app/views/layouts/_messages.html.erb
<% flash.each do |type, content| %>
  <div class="ui info <%= type %> message transition">
    <div class="header">
      <%= content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="item" href='/'>
  Chatroom
</a>
<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to 'Log out', logout_path, method: :delete, class: "item" %>
      <% else %>
        <%= link_to 'Log in', login_path, class: "item" %>
      <% end %>
    </div>
  </div>
  <% unless logged_in? %>
    <div class="item">
      <%= link_to 'Login', login_path, class: "ui primary button" %>    
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Message</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui large menu inverted">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
        <%= render 'layouts/header' %>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>    
    </div>
  </body>
</html>